source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'phlex', '1.0.0.rc1'
gem 'phlex-rails'
gem 'proscenium', path: '/Users/joelmoss/dev/proscenium'
gem 'puma', '~> 5.0'
gem 'rails', '~> 7.0.4'
